#!/bin/sh
# 
#The file is derived by modifying the "13000_generic_vtol_standard" airframe file.
#
# @name LEAP VTOL
#
# @type Standard VTOL
# @class VTOL
#
# @maintainer gkashyap
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 motor 5
# @output MAIN6 motor 6
# @output MAIN7 motor 7
# @output MAIN8 motor 8
# @output AUX1 Aileron 1
# @output AUX2 Aileron 2
# @output AUX3 Elevator
# @output AUX4 Rudder
# @output AUX5 Throttle
#


sh /etc/init.d/rc.leap_defaults



if [ $AUTOCNF = yes ]
then
	param set MC_PITCH_P 4
	param set MC_PITCHRATE_P 0.5
	param set MC_PITCHRATE_I 0.09
	param set MC_PITCHRATE_D 0.013
	param set MC_PITCHRATE_MAX 180

	param set MC_ROLL_P 4
	param set MC_ROLLRATE_P 0.5
	param set MC_ROLLRATE_I 0.1
	param set MC_ROLLRATE_D 0.007
	param set MC_ROLLRATE_MAX 180

	param set MC_YAW_P 3
	param set MC_YAWRATE_P 0.5
	param set MC_YAWRATE_I 0.3
	param set MC_YAWRATE_D 0

	param set MPC_HOLD_MAX_XY 0.25
	param set MPC_THR_MIN 0.15
	param set MPC_Z_VEL_MAX_DN 2

	param set BAT_N_CELLS 4

	param set PWM_AUX_DIS5 950

	param set VT_TYPE 2
	param set VT_MOT_ID 12345678
	param set VT_FW_MOT_OFFID 12345678

	param set ATT_MAG_DECL -1.26
fi

set MAV_TYPE 22

set MIXER octo_cox_w
set MIXER_AUX vtol_AAERT

set PWM_OUT 12345678
