#!/bin/sh
#
# @name Leap VTOL
#
# @type Standard VTOL
#

sh /etc/init.d/rc.leap_defaults

if [ $AUTOCNF = yes ]
then
	param set MC_PITCH_P 4
	param set MC_PITCHRATE_P 0.24
	param set MC_PITCHRATE_I 0.09
	param set MC_PITCHRATE_D 0.013
	param set MC_PITCHRATE_MAX 180

	param set MC_ROLL_P 4
	param set MC_ROLLRATE_P 0.16
	param set MC_ROLLRATE_I 0.07
	param set MC_ROLLRATE_D 0.009
	param set MC_ROLLRATE_MAX 180

	param set MC_YAW_P 3
	param set MC_YAWRATE_P 0.2
	param set MC_YAWRATE_I 0.1
	param set MC_YAWRATE_D 0

	param set MPC_HOLD_MAX_XY 0.25
	param set MPC_THR_MIN 0.15
	param set MPC_Z_VEL_MAX_DN 2
	
	param set FW_AIRSPD_MAX 25
	param set FW_AIRSPD_MIN 14
	param set FW_AIRSPD_TRIM 16

	param set MIS_LTRMIN_ALT 10
	param set MIS_TAKEOFF_ALT 10
	param set MIS_YAW_TMT 10

	param set MPC_ACC_HOR_MAX 2
	param set MPC_ACC_HOR_MAX 2
	param set MPC_TKO_SPEED 1
	param set MPC_XY_P 0.8
	param set MPC_XY_VEL_D 0.005
	param set MPC_XY_VEL_I 0.2
	param set MPC_XY_VEL_P 0.15

	param set NAV_ACC_RAD 5
	param set NAV_LOITER_RAD 80

	param set VT_F_TRANS_DUR 5
	param set VT_F_TRANS_THR 0.75
	param set VT_ARSP_TRANS 16

	param set VT_TYPE 2
	param set VT_MOT_ID 12345678
	param set VT_FW_MOT_OFFID 12345678

fi

set MAV_TYPE 22

set MIXER_FILE etc/mixers-sitl/leap_vtol_sitl.main.mix
set MIXER custom
